version: 2.1

executors:
  python:
    docker:
      - image: circleci/python:3.7.5-stretch

defaults: &defaults
  executor: python

orbs:
  docker: circleci/docker@0.5.20


jobs:

  build_and_test:
    <<: *defaults

    steps:
      - run: &setup_env_vars
          name: Setup Environment Variables
          command: |
            export PROJECT_NAME=ml-recipe-seismic
            export PROJECT_PATH_STORAGE=storage:build-$PROJECT_NAME-$CIRCLE_WORKFLOW_ID
            export IMAGE_NAME=neuromation/$PROJECT_NAME
            export IMAGE_REF=$IMAGE_NAME:build-$CIRCLE_WORKFLOW_ID
            export JOBS_TAG=build-$CIRCLE_WORKFLOW_ID

            echo "PROJECT_NAME=$PROJECT_NAME" >> $BASH_ENV
            echo "PROJECT_PATH_STORAGE=$PROJECT_PATH_STORAGE" >> $BASH_ENV
            echo "IMAGE_NAME=$IMAGE_NAME" >> $BASH_ENV
            echo "IMAGE_REF=$IMAGE_REF" >> $BASH_ENV
            echo "JOBS_TAG=$JOBS_TAG" >> $BASH_ENV

      - setup_remote_docker
      - checkout
      - run: &install_dependencies
          name: Install Dependencies, Configure Environment
          command: |
            pip install --user --no-cache-dir -r .circleci/requirements.txt
            pip install --user --no-cache-dir neuromation==20.6.10  # test against neuro with the old attach-exec
            neuro config login-with-token $NEURO_TOKEN $NEURO_URL
            neuro config switch-cluster $NEURO_CLUSTER
            neuro config show

      - run:
          name: Build and Test Image
          command: |
            export CUSTOM_ENV=image:$IMAGE_REF
            make setup __BAKE_SETUP=yes | tee
            echo "Running jobs with unique tag: $JOBS_TAG"
            export RUN_EXTRA="--tag=$JOBS_TAG"

            # NOTE: Notebook fails with "Kernel died" error on cpu-small (2.0G memory)
            # make -f test.mk test_jupyter PRESET=cpu-large | tee
            # make -f test.mk test_jupyter PRESET=gpu-small | tee
            make -f test.mk test_jupyter_baked PRESET=cpu-large | tee
            make -f test.mk test_jupyter_baked PRESET=gpu-small | tee

      - run:
          name: Cleanup Jobs
          command: |
            echo JOBS_TAG="$JOBS_TAG"
            export JOBS_LEFT=$(neuro -q ps --tag=$JOBS_TAG)
            echo JOBS_LEFT="$JOBS_LEFT"
            [ ! "$JOBS_LEFT" ] || neuro kill $JOBS_LEFT
          when: always

  deploy:
    <<: *defaults
    steps:
      - run: *setup_env_vars
      - setup_remote_docker
      - checkout
      - run: *install_dependencies

      - run:
          name: Pull Image
          command: |
            neuro config docker
            neuro pull image:$IMAGE_REF | tee
            docker tag $IMAGE_REF $IMAGE_NAME:$CIRCLE_TAG
            docker tag $IMAGE_REF $IMAGE_NAME:latest

      - docker/check
      - docker/push:
          image: $IMAGE_NAME
          tag: $CIRCLE_TAG,latest


workflows:
  version: 2

  main:
    jobs:

      - build_and_test:
          filters:
            tags:
              only:
                - /.*/

      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only:
                - /.*/
